In [3]:
import numpy as np

In [ ]:
5+5

In [ ]:
a = above

In [6]:
6+6

12

In [ ]:
b = below

## Ini adalah Markdown

## Belajar Numpy

In [8]:
# List Basic
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [10]:
### Array
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [11]:
type(b)

numpy.ndarray

n = jumlah
d = dimensi
array

In [14]:
## Elementwise
a + [1]

[1, 2, 3, 4, 5, 1]

In [15]:
b + 1 ## Bersifat elementwise => operasi dilakukan ke setiap element dari array

array([2, 3, 4, 5, 6])

In [16]:
a * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
b * 2

array([ 2,  4,  6,  8, 10])

### Range dari Python

In [22]:
range(5, 10, 0.5) # Built in dari Python

TypeError: 'float' object cannot be interpreted as an integer

### Range dari Numpy

In [20]:

np.arange(5,10, 0.5) ## Range dari python ==> STEP dapat dengan/menggunakan FLOAT

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [23]:
### Linspace => Linear space

In [24]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [25]:
### Array Multi dimensi => Matrix

In [26]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [29]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [32]:
aNum = np.array(a)
aNum

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
b

array([1, 2, 3, 4, 5])

In [35]:
b.ndim

1

In [36]:
aNum.ndim

2

In [37]:
b.size

5

In [38]:
aNum.size

9

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [49]:
aNum = np.array(a)
bNum = np.array(b)

In [50]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [51]:
aNum + bNum

array([ 7,  9, 11, 13, 15])

In [52]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [53]:
aNum * bNum

array([ 6, 14, 24, 36, 50])

In [54]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [55]:
aNum - bNum

array([-5, -5, -5, -5, -5])

In [56]:
aNum = np.arange(10) ** 2

In [57]:
aNum

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [58]:
aNum[2]

4

In [59]:
aNum[-1]

81

In [60]:
aNum[4]

16

In [61]:
aNum[1:4]

array([1, 4, 9], dtype=int32)

In [62]:
aNum[:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [63]:
aNum[5:]

array([25, 36, 49, 64, 81], dtype=int32)

In [64]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [65]:
aMatrix = np.array(a)

In [66]:
aMatrix[0][2]

3

In [67]:
A = [
    [2, 3, 4],
    [4, 5, 6]
]

In [68]:
AMt = np.array(A)

In [71]:
AMt.shape

(2, 3)

In [73]:
AMt

array([[2, 3, 4],
       [4, 5, 6]])

In [76]:
AMt.transpose()

array([[2, 4],
       [3, 5],
       [4, 6]])

In [77]:
np.transpose(AMt)

array([[2, 4],
       [3, 5],
       [4, 6]])

In [78]:
AMt.T

array([[2, 4],
       [3, 5],
       [4, 6]])

In [79]:
AMt.reshape(6,1)

array([[2],
       [3],
       [4],
       [4],
       [5],
       [6]])

In [80]:
AMt.reshape(1,6)

array([[2, 3, 4, 4, 5, 6]])

In [81]:
AMt.reshape(3, 2)

array([[2, 3],
       [4, 4],
       [5, 6]])

In [82]:
#### Statistics Operational

In [84]:
B = np.array([2, 50, 26, 23, 10, 3, 1, 100, 10, 8])

In [85]:
np.mean(B)

23.3

In [86]:
np.median(B)

10.0

In [87]:
np.percentile(B, 25) # Q1 => Quartile 1 = 25%

4.25

In [88]:
np.percentile(B, 75) # Q3 => Quartile 3 = 75%

25.25

In [89]:
np.max(B)

100

In [90]:
np.min(B)

1

In [91]:
np.sort(B)

array([  1,   2,   3,   8,  10,  10,  23,  26,  50, 100])

In [92]:
np.argmax(B)

7

In [93]:
np.argmin(B)

6

In [94]:
##### Membuat angka Random

In [95]:
np.random.rand(10) ## antara nilai 0-1

array([0.75331069, 0.37679627, 0.69229612, 0.60588473, 0.06495015,
       0.61421043, 0.05658903, 0.25120701, 0.17142313, 0.67376319])

In [97]:
np.random.randn(10) ## antara -3 sampai 3 tetapi berbentuk Bell shaped (Distribusi Normal)

array([ 1.17957923,  0.17343628, -0.74246768,  0.05220565,  1.17046878,
       -1.51488645,  0.58247411, -0.24530143,  0.75923687, -0.02801411])

In [99]:
np.random.randint(1, 10, 10)

array([1, 1, 5, 3, 6, 3, 5, 2, 5, 3])

In [100]:
import pandas as pd

pd = pandas dataframe

In [101]:
##### Series

In [102]:
x = [9, 10, 8, 15, 3, 17]

In [104]:
x1 = np.array(x)
x1

array([ 9, 10,  8, 15,  3, 17])

In [105]:
y = pd.Series(x)
y

0     9
1    10
2     8
3    15
4     3
5    17
dtype: int64

In [106]:
ind = ['a', 'b', 'c', 'd', 'e', 'f']

In [108]:
pd.Series(data=x1, index=ind, name='Test')

a     9
b    10
c     8
d    15
e     3
f    17
Name: Test, dtype: int32

In [109]:
data = {'a' : 50,
       'b' : 75,
       'c' : 85}

In [110]:
pd.Series(data)

a    50
b    75
c    85
dtype: int64

In [111]:
#### DataFrame

In [112]:
x = [20, 50, 35, 13]
x1 = np.array(x)

In [113]:
df = pd.DataFrame(x1, columns=['Usia'])
df

Usia
0    20
1    50
2    35
3    13

In [114]:
data =[
    ["Rosi", 25, "Jakarta"],
    ["Selvy", 24, "Bandung"],
    ["Rita", 27, "Malang"],
    ["Sony", 26, "Bandung"]
]

In [115]:
df = pd.DataFrame(data, columns=['nama', 'usia', 'kota'])

In [116]:
df

nama  usia     kota
0   Rosi    25  Jakarta
1  Selvy    24  Bandung
2   Rita    27   Malang
3   Sony    26  Bandung

In [117]:
df = pd.read_csv('sales.csv')
df

Country Region Sales Person    Date of Purchase     Total  Quantity
0       India   East         John    3/1/2013 0:00:00  26000000       567
1       China  North         Bill  12/29/2016 0:00:00    100000      3000
2          UK   East       Thomas   1/13/2014 0:00:00    120000       345
3       Nepal   East         John    4/2/2010 0:00:00    200000      1000
4      Africa   East         Bill  10/16/2015 0:00:00    220000       123
5     Bhuthan  North       Thomas    4/1/2013 0:00:00    240000      1000
6     Mylasia  North         John   1/17/2016 0:00:00    260000      7890
7       India  North         Bill   7/11/2017 0:00:00    220000       200
8       Nepal   East       Thomas    7/7/2014 0:00:00    240000      1000
9       Korea  North         John   8/15/2013 0:00:00    260000      1000
10  Australia  North         Bill   6/21/2012 0:00:00    140000       567
11     Africa   East       Thomas   6/19/2015 0:00:00    150000      1000
12  Australia   East         John    3/4/2017 0:00:00    160000       892
13      Nepal   East         Bill  11/24/2013 0:00:00    200000       444
14      India   East       Thomas   8/31/2014 0:00:00    220000       345
15    Toranto   West         John   9/13/2018 0:00:00    240000      1000
16         UK   West         Bill    8/5/2015 0:00:00    260000       123
17     Quatar   West       Thomas   6/30/2013 0:00:00    260000      1000
18     Africa  North         John  11/30/2015 0:00:00    140000      7890
19      Nepal  North         Bill   12/2/2016 0:00:00    150000       200

In [118]:
df.head()

Country Region Sales Person    Date of Purchase     Total  Quantity
0   India   East         John    3/1/2013 0:00:00  26000000       567
1   China  North         Bill  12/29/2016 0:00:00    100000      3000
2      UK   East       Thomas   1/13/2014 0:00:00    120000       345
3   Nepal   East         John    4/2/2010 0:00:00    200000      1000
4  Africa   East         Bill  10/16/2015 0:00:00    220000       123

In [119]:
df.tail()

Country Region Sales Person    Date of Purchase   Total  Quantity
15  Toranto   West         John   9/13/2018 0:00:00  240000      1000
16       UK   West         Bill    8/5/2015 0:00:00  260000       123
17   Quatar   West       Thomas   6/30/2013 0:00:00  260000      1000
18   Africa  North         John  11/30/2015 0:00:00  140000      7890
19    Nepal  North         Bill   12/2/2016 0:00:00  150000       200

In [121]:
df.isna().sum()
## Mencari Missing Value

Country             0
Region              0
Sales Person        0
Date of Purchase    0
Total               0
Quantity            0
dtype: int64

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Country           20 non-null     object
 1   Region            20 non-null     object
 2   Sales Person      20 non-null     object
 3   Date of Purchase  20 non-null     object
 4   Total             20 non-null     int64 
 5   Quantity          20 non-null     int64 
dtypes: int64(2), object(4)
memory usage: 1.1+ KB


In [123]:
df.describe().T

count       mean           std       min       25%       50%  \
Total      20.0  1489000.0  5.769521e+06  100000.0  150000.0  220000.0   
Quantity   20.0     1479.3  2.279447e+03     123.0     345.0     946.0   

               75%         max  
Total     245000.0  26000000.0  
Quantity    1000.0      7890.0

In [124]:
df.describe(include='O')

Country Region Sales Person   Date of Purchase
count       20     20           20                 20
unique      11      3            3                 20
top      Nepal   East         Bill  12/2/2016 0:00:00
freq         4      9            7                  1

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Country           20 non-null     object
 1   Region            20 non-null     object
 2   Sales Person      20 non-null     object
 3   Date of Purchase  20 non-null     object
 4   Total             20 non-null     int64 
 5   Quantity          20 non-null     int64 
dtypes: int64(2), object(4)
memory usage: 1.1+ KB


In [127]:
df.dtypes

Country             object
Region              object
Sales Person        object
Date of Purchase    object
Total                int64
Quantity             int64
dtype: object

In [128]:
df.isna().sum()

Country             0
Region              0
Sales Person        0
Date of Purchase    0
Total               0
Quantity            0
dtype: int64

In [ ]:
Exploratory Data Analysis --- EDA
(Harus menguasai Domain/Business Knowledge)

- Pengecekan Tipe Data
- Pengecekan Missing Value - Dan Kita Handling
- Describe Data
- Pengecekan Data Outliers & Kita Handling
- Pengecekan - Extraksi Data datetime/Tanggal jika diperlukan

### Analisa Data
- Univariate (Kolom Tunggal)
- BiVariate / Multivariate (Multi Kolom)
 Ambil Insight - Interpretasi dari Hasil Analisa 
    
Data Visualization
- Univariate
- Bivariate/Multivariate (Multikolom)
Ambil Insight - Interpretasi dari Grafik

-- Kesimpulan & Saran

##### Machine Learning
