# Numpy

In [1]:
import numpy as np

C:\Users\Damianus Deni\AppData\Roaming\Python\Python37\site-packages\ipykernel\parentpoller.py:113: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")


### Basic array
1. List vs Array

In [9]:
# List
a = [1,2,3,4,5]
a, f"type: {type(a)}" 

([1, 2, 3, 4, 5], "type: <class 'list'>")

In [8]:
# Array
b = np.array(a)
b, f"type: {type(b)}" # --> n = jumlah d = dimensi array

(array([1, 2, 3, 4, 5]), "type: <class 'numpy.ndarray'>")

2. Array is Elementwise

In [10]:
# if list got operated (+ - : *)
print(f"list: {a}")
print(f"list a plus 1: {a + [1]}")

list: [1, 2, 3, 4, 5]
list a plus 1: [1, 2, 3, 4, 5, 1]


In [13]:
# if array got operated (+ - : *)
print(f"list: {b}")
print(f"list b plus 1: {b + [1]} --> '1' will be added to each element, \nthis is called elementwise")

list: [1 2 3 4 5]
list b plus 1: [2 3 4 5 6] --> '1' will be added to each element, 
this is called elementwise


In [14]:
a * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [15]:
b * 2

array([ 2,  4,  6,  8, 10])

### Range
1. Python Range

In [19]:
range(5, 10, 0.5) 
# Built in from Python
# cannot accept step in float

TypeError: 'float' object cannot be interpreted as an integer

2. Numpy Range

In [17]:
np.arange(5,10, 0.5) 
# step can use FLOAT

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Matrix

list of numpy use --> to generate list of numbers
- np.nan = creating missing value
- np.linspace
- np.arange
- np.random.randint
- np.random
- np.logspace

In [21]:
### Array Multi dimensi => Matrix
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [32]:
aNum = np.array(a)
aNum

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Linspace => Linear space
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [33]:
b

array([1, 2, 3, 4, 5])

In [35]:
b.ndim

1

In [36]:
aNum.ndim

2

In [37]:
b.size

5

In [38]:
aNum.size

9

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [49]:
aNum = np.array(a)
bNum = np.array(b)

In [50]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [51]:
aNum + bNum

array([ 7,  9, 11, 13, 15])

In [52]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [53]:
aNum * bNum

array([ 6, 14, 24, 36, 50])

In [54]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [55]:
aNum - bNum

array([-5, -5, -5, -5, -5])

In [56]:
aNum = np.arange(10) ** 2

In [57]:
aNum

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [58]:
aNum[2]

4

In [59]:
aNum[-1]

81

In [60]:
aNum[4]

16

In [61]:
aNum[1:4]

array([1, 4, 9], dtype=int32)

In [62]:
aNum[:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [63]:
aNum[5:]

array([25, 36, 49, 64, 81], dtype=int32)

In [64]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [65]:
aMatrix = np.array(a)

In [66]:
aMatrix[0][2]

3

In [67]:
A = [
    [2, 3, 4],
    [4, 5, 6]
]

In [68]:
AMt = np.array(A)

In [71]:
AMt.shape

(2, 3)

In [73]:
AMt

array([[2, 3, 4],
       [4, 5, 6]])

In [76]:
AMt.transpose()

array([[2, 4],
       [3, 5],
       [4, 6]])

In [77]:
np.transpose(AMt)

array([[2, 4],
       [3, 5],
       [4, 6]])

In [78]:
AMt.T

array([[2, 4],
       [3, 5],
       [4, 6]])

In [79]:
AMt.reshape(6,1)

array([[2],
       [3],
       [4],
       [4],
       [5],
       [6]])

In [80]:
AMt.reshape(1,6)

array([[2, 3, 4, 4, 5, 6]])

In [81]:
AMt.reshape(3, 2)

array([[2, 3],
       [4, 4],
       [5, 6]])

In [82]:
#### Statistics Operational

In [84]:
B = np.array([2, 50, 26, 23, 10, 3, 1, 100, 10, 8])

In [85]:
np.mean(B)

23.3

In [86]:
np.median(B)

10.0

In [87]:
np.percentile(B, 25) # Q1 => Quartile 1 = 25%

4.25

In [88]:
np.percentile(B, 75) # Q3 => Quartile 3 = 75%

25.25

In [89]:
np.max(B)

100

In [90]:
np.min(B)

1

In [91]:
np.sort(B)

array([  1,   2,   3,   8,  10,  10,  23,  26,  50, 100])

In [92]:
np.argmax(B)

7

In [93]:
np.argmin(B)

6

In [94]:
##### Membuat angka Random

In [95]:
np.random.rand(10) ## antara nilai 0-1

array([0.75331069, 0.37679627, 0.69229612, 0.60588473, 0.06495015,
       0.61421043, 0.05658903, 0.25120701, 0.17142313, 0.67376319])

In [97]:
np.random.randn(10) ## antara -3 sampai 3 tetapi berbentuk Bell shaped (Distribusi Normal)

array([ 1.17957923,  0.17343628, -0.74246768,  0.05220565,  1.17046878,
       -1.51488645,  0.58247411, -0.24530143,  0.75923687, -0.02801411])

In [99]:
np.random.randint(1, 10, 10)

array([1, 1, 5, 3, 6, 3, 5, 2, 5, 3])

# Basic Pandas

In [57]:
import pandas as pd

### 1) Series & Dataframe
#### Series vs Array

In [22]:
x = [9, 10, 8, 15, 3, 17]

In [26]:
# Convert list x to array
x_array = np.array(x)
x_array

array([ 9, 10,  8, 15,  3, 17])

In [27]:
# Convert list x to series
# series is one of columns with rows that will be used in dataframe (table)
x_series = pd.Series(x)
x_series

0     9
1    10
2     8
3    15
4     3
5    17
dtype: int64

In [31]:
# Setting custom index for series
i = ['a', 'b', 'c', 'd', 'e', 'f']

In [30]:
pd.Series(data=x1, index=i, name='Test')

a     9
b    10
c     8
d    15
e     3
f    17
Name: Test, dtype: int32

In [109]:
data = {'a' : 50,
       'b' : 75,
       'c' : 85}

In [110]:
pd.Series(data)

a    50
b    75
c    85
dtype: int64

#### DataFrame

In [33]:
# Convert array to dataframe
x = [20, 50, 35, 13]
x_array = np.array(x)

In [32]:
df = pd.DataFrame(x_array, columns=['Age'])
df

Age
0    9
1   10
2    8
3   15
4    3
5   17

In [34]:
# Convert list to dataframe
data =[
    ["Rosi", 25, "Jakarta"],
    ["Selvy", 24, "Bandung"],
    ["Rita", 27, "Malang"],
    ["Sony", 26, "Bandung"]
]

In [35]:
df = pd.DataFrame(data, columns=['name', 'age', 'city'])

In [36]:
df

name  age     city
0   Rosi   25  Jakarta
1  Selvy   24  Bandung
2   Rita   27   Malang
3   Sony   26  Bandung

#### Accessing external files

In [43]:
df = pd.read_csv('../data/sales.csv')
df

Country Region Sales Person    Date of Purchase     Total  Quantity
0       India   East         John    3/1/2013 0:00:00  26000000       567
1       China  North         Bill  12/29/2016 0:00:00    100000      3000
2          UK   East       Thomas   1/13/2014 0:00:00    120000       345
3       Nepal   East         John    4/2/2010 0:00:00    200000      1000
4      Africa   East         Bill  10/16/2015 0:00:00    220000       123
5     Bhuthan  North       Thomas    4/1/2013 0:00:00    240000      1000
6     Mylasia  North         John   1/17/2016 0:00:00    260000      7890
7       India  North         Bill   7/11/2017 0:00:00    220000       200
8       Nepal   East       Thomas    7/7/2014 0:00:00    240000      1000
9       Korea  North         John   8/15/2013 0:00:00    260000      1000
10  Australia  North         Bill   6/21/2012 0:00:00    140000       567
11     Africa   East       Thomas   6/19/2015 0:00:00    150000      1000
12  Australia   East         John    3/4/2017 0:00:00    160000       892
13      Nepal   East         Bill  11/24/2013 0:00:00    200000       444
14      India   East       Thomas   8/31/2014 0:00:00    220000       345
15    Toranto   West         John   9/13/2018 0:00:00    240000      1000
16         UK   West         Bill    8/5/2015 0:00:00    260000       123
17     Quatar   West       Thomas   6/30/2013 0:00:00    260000      1000
18     Africa  North         John  11/30/2015 0:00:00    140000      7890
19      Nepal  North         Bill   12/2/2016 0:00:00    150000       200

In [44]:
# Accessing top-5 rows
df.head()

Country Region Sales Person    Date of Purchase     Total  Quantity
0   India   East         John    3/1/2013 0:00:00  26000000       567
1   China  North         Bill  12/29/2016 0:00:00    100000      3000
2      UK   East       Thomas   1/13/2014 0:00:00    120000       345
3   Nepal   East         John    4/2/2010 0:00:00    200000      1000
4  Africa   East         Bill  10/16/2015 0:00:00    220000       123

In [45]:
# Accessing 5 rows from bottom
df.tail()

Country Region Sales Person    Date of Purchase   Total  Quantity
15  Toranto   West         John   9/13/2018 0:00:00  240000      1000
16       UK   West         Bill    8/5/2015 0:00:00  260000       123
17   Quatar   West       Thomas   6/30/2013 0:00:00  260000      1000
18   Africa  North         John  11/30/2015 0:00:00  140000      7890
19    Nepal  North         Bill   12/2/2016 0:00:00  150000       200

In [46]:
# Checking missing values
df.isna().sum()

Country             0
Region              0
Sales Person        0
Date of Purchase    0
Total               0
Quantity            0
dtype: int64

In [53]:
# Info - type of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
Country             20 non-null object
Region              20 non-null object
Sales Person        20 non-null object
Date of Purchase    20 non-null object
Total               20 non-null int64
Quantity            20 non-null int64
dtypes: int64(2), object(4)
memory usage: 1.1+ KB


In [56]:
# Info - type of data for each column
df.dtypes

Country             object
Region              object
Sales Person        object
Date of Purchase    object
Total                int64
Quantity             int64
dtype: object

In [54]:
# Info - statistics info for numeric data
df.describe()
# df.describe().T # to transform into horizontal view

Total     Quantity
count  2.000000e+01    20.000000
mean   1.489000e+06  1479.300000
std    5.769521e+06  2279.447258
min    1.000000e+05   123.000000
25%    1.500000e+05   345.000000
50%    2.200000e+05   946.000000
75%    2.450000e+05  1000.000000
max    2.600000e+07  7890.000000

In [55]:
# Info - statistics info for categorical data
df.describe(include='O')

Country Region Sales Person   Date of Purchase
count       20     20           20                 20
unique      11      3            3                 20
top      Nepal   East         John  6/19/2015 0:00:00
freq         4      9            7                  1

### 2) Slicing dataframe and running statistic function on dataframe

In [2]:
data =[
    ["Rosi", 25, "Jakarta"],
    ["Selvy", 24, "Bandung"],
    ["Rita", 27, "Malang"],
    ["Sony", 26, "Bandung"]
]

In [3]:
df = pd.DataFrame(data, columns=['nama', 'usia', 'kota'], index=['A', 'B', 'C', 'D'])
df

nama  usia     kota
A   Rosi    25  Jakarta
B  Selvy    24  Bandung
C   Rita    27   Malang
D   Sony    26  Bandung

In [8]:
df['nama']

A     Rosi
B    Selvy
C     Rita
D     Sony
Name: nama, dtype: object

In [9]:
df[['nama', 'kota']]

nama     kota
A   Rosi  Jakarta
B  Selvy  Bandung
C   Rita   Malang
D   Sony  Bandung

In [11]:
df['nama']['B']

'Selvy'

In [14]:
# df['gaji'] = 20000000
df['gaji'] = [20000000, 15000000, 13000000, 30000000]

In [15]:
df

nama  usia     kota      gaji
A   Rosi    25  Jakarta  20000000
B  Selvy    24  Bandung  15000000
C   Rita    27   Malang  13000000
D   Sony    26  Bandung  30000000

In [18]:
df['gaji'].mean()

19500000.0

In [19]:
df['gaji'].median()

17500000.0

In [20]:
df['gaji'].sum()

78000000

In [22]:
df['gaji'].std()

7593857.166596345

In [25]:
# Pandas = std sample 
# Numpy = std populasi 

# pandas miu, klu di numpy s

In [24]:
df.describe()

# jika kolom gaji hanya satu data, berapa std nya? 

usia          gaji
count   4.000000  4.000000e+00
mean   25.500000  1.950000e+07
std     1.290994  7.593857e+06
min    24.000000  1.300000e+07
25%    24.750000  1.450000e+07
50%    25.500000  1.750000e+07
75%    26.250000  2.250000e+07
max    27.000000  3.000000e+07

### 3) Accessing & Modifying Data in Dataframe

In [61]:
data = np.random.randn(5,4)

# rand -> angka yang dihasilkan antara 0 - 1
# randn -> membentuk distribusi normal dengan angka -3 sampai 3

In [62]:
data

array([[ 0.79776362, -1.96806689, -1.9084271 , -1.10755996],
       [-0.25826572, -0.55819045, -0.3980215 ,  1.52793278],
       [-0.71172992, -0.14508059, -0.61202246,  0.54464168],
       [-0.1560472 ,  0.21286727,  1.21396802,  0.35437781],
       [-1.8764061 ,  0.50205769, -0.39588163, -1.09977363]])

In [63]:
df = pd.DataFrame(data, columns='W,X,Y,Z'.split(','), index = 'A B C D E'.split(' '))
df

W         X         Y         Z
A  0.797764 -1.968067 -1.908427 -1.107560
B -0.258266 -0.558190 -0.398021  1.527933
C -0.711730 -0.145081 -0.612022  0.544642
D -0.156047  0.212867  1.213968  0.354378
E -1.876406  0.502058 -0.395882 -1.099774

In [32]:
df[['X', 'Y']]

X         Y
A -0.296037 -0.907984
B  0.723927  1.036089
C  0.702701  1.235684
D  0.113500  0.712243
E -0.743221  0.753674

#### Add Columns

In [64]:
# Add Columns
df['col_1'] = df['X'] * df['Y']
df

W         X         Y         Z     col_1
A  0.797764 -1.968067 -1.908427 -1.107560  3.755912
B -0.258266 -0.558190 -0.398021  1.527933  0.222172
C -0.711730 -0.145081 -0.612022  0.544642  0.088793
D -0.156047  0.212867  1.213968  0.354378  0.258414
E -1.876406  0.502058 -0.395882 -1.099774 -0.198755

In [72]:
df['col_2'] = [i ** 2 for i in range(1,6)]
df

W         X         Y         Z     col_1  col_2
A  0.797764 -1.968067 -1.908427 -1.107560  3.755912      1
B -0.258266 -0.558190 -0.398021  1.527933  0.222172      4
C -0.711730 -0.145081 -0.612022  0.544642  0.088793      9
D -0.156047  0.212867  1.213968  0.354378  0.258414     16
E -1.876406  0.502058 -0.395882 -1.099774 -0.198755     25

#### Remove Data

In [73]:
df.drop('C')

W         X         Y         Z     col_1  col_2
A  0.797764 -1.968067 -1.908427 -1.107560  3.755912      1
B -0.258266 -0.558190 -0.398021  1.527933  0.222172      4
D -0.156047  0.212867  1.213968  0.354378  0.258414     16
E -1.876406  0.502058 -0.395882 -1.099774 -0.198755     25

In [ ]:
# Secara default nilai Axis adalah 0

Axis 0 => row -> droping Row C
Axis 1 => column -> droping Column col_2

In [75]:
df.drop('C', axis=0) # similar to df.drop('C')

W         X         Y         Z     col_1  col_2
A  0.797764 -1.968067 -1.908427 -1.107560  3.755912      1
B -0.258266 -0.558190 -0.398021  1.527933  0.222172      4
D -0.156047  0.212867  1.213968  0.354378  0.258414     16
E -1.876406  0.502058 -0.395882 -1.099774 -0.198755     25

In [77]:
df.drop('col_2', axis=1)

W         X         Y         Z     col_1
A  0.797764 -1.968067 -1.908427 -1.107560  3.755912
B -0.258266 -0.558190 -0.398021  1.527933  0.222172
C -0.711730 -0.145081 -0.612022  0.544642  0.088793
D -0.156047  0.212867  1.213968  0.354378  0.258414
E -1.876406  0.502058 -0.395882 -1.099774 -0.198755

In [78]:
df.drop(columns=['col_1', 'X'])

W         Y         Z  col_2
A  0.797764 -1.908427 -1.107560      1
B -0.258266 -0.398021  1.527933      4
C -0.711730 -0.612022  0.544642      9
D -0.156047  1.213968  0.354378     16
E -1.876406 -0.395882 -1.099774     25

Agar Fungsi mengubah Data yang ada
- assign nama dataframe original
- gunakan parameter 'inplace = True'

In [42]:
df_del = df.drop(columns='col_1')
df_del

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1
B -0.419792  0.723927  1.036089 -1.343167      4
C  1.893363  0.702701  1.235684 -1.459479      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594 -0.743221  0.753674 -0.845777     25

In [43]:
df.drop(columns='col_1', inplace=True)
df

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1
B -0.419792  0.723927  1.036089 -1.343167      4
C  1.893363  0.702701  1.235684 -1.459479      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594 -0.743221  0.753674 -0.845777     25

In [44]:
# selecting column X
df['X']

A   -0.296037
B    0.723927
C    0.702701
D    0.113500
E   -0.743221
Name: X, dtype: float64

In [79]:
# selecting column X and row B & D
df['X'][['B', 'D']]

B   -0.558190
D    0.212867
Name: X, dtype: float64

In [80]:
df

W         X         Y         Z     col_1  col_2
A  0.797764 -1.968067 -1.908427 -1.107560  3.755912      1
B -0.258266 -0.558190 -0.398021  1.527933  0.222172      4
C -0.711730 -0.145081 -0.612022  0.544642  0.088793      9
D -0.156047  0.212867  1.213968  0.354378  0.258414     16
E -1.876406  0.502058 -0.395882 -1.099774 -0.198755     25

#### Accessing Row Data with `.loc` and `.iloc`
`.loc` digunakan untuk mengakses baris data menggunakan **nama/label index**

In [83]:
df.loc['C']

W       -0.711730
X       -0.145081
Y       -0.612022
Z        0.544642
col_1    0.088793
col_2    9.000000
Name: C, dtype: float64

In [82]:
df.loc['E']

W        -1.876406
X         0.502058
Y        -0.395882
Z        -1.099774
col_1    -0.198755
col_2    25.000000
Name: E, dtype: float64

`.iloc` digunakan untuk mengakses baris data menggunakan **Urutan Index**

In [84]:
df.iloc[2]

W       -0.711730
X       -0.145081
Y       -0.612022
Z        0.544642
col_1    0.088793
col_2    9.000000
Name: C, dtype: float64

In [85]:
df.iloc[4]

W        -1.876406
X         0.502058
Y        -0.395882
Z        -1.099774
col_1    -0.198755
col_2    25.000000
Name: E, dtype: float64

In [86]:
df.loc[['C', 'D']]

W         X         Y         Z     col_1  col_2
C -0.711730 -0.145081 -0.612022  0.544642  0.088793      9
D -0.156047  0.212867  1.213968  0.354378  0.258414     16

In [87]:
# selecting row C & D and column Y & Z
df.loc[['C', 'D']][['Y', 'Z']]

Y         Z
C -0.612022  0.544642
D  1.213968  0.354378

In [88]:
# selecting column Y & Z and row D & C
df[['Y', 'Z']].loc[['D', 'C']]

Y         Z
D  1.213968  0.354378
C -0.612022  0.544642

### 4) Subsetting
- List = Slicing
- Pandas = Subsetting
    > it is to display certain data with certain conditions

In [90]:
# to display value < 0 as NaN
df[ df > 0 ]
# NaN = Not a Number ==> Missing Value

W         X         Y         Z     col_1  col_2
A  0.797764       NaN       NaN       NaN  3.755912      1
B       NaN       NaN       NaN  1.527933  0.222172      4
C       NaN       NaN       NaN  0.544642  0.088793      9
D       NaN  0.212867  1.213968  0.354378  0.258414     16
E       NaN  0.502058       NaN       NaN       NaN     25

In [64]:
df1 = df[df>0]

In [67]:
df

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1
B -0.419792  0.723927  1.036089 -1.343167      4
C  1.893363  0.702701  1.235684 -1.459479      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594 -0.743221  0.753674 -0.845777     25

In [91]:
# to display data with iloc
df.iloc[1:5][['X', 'Z']]

X         Z
B -0.558190  1.527933
C -0.145081  0.544642
D  0.212867  0.354378
E  0.502058 -1.099774

In [93]:
# to display row where column W's value is greater than 0
df[df['W'] > 0]

W         X         Y        Z     col_1  col_2
A  0.797764 -1.968067 -1.908427 -1.10756  3.755912      1

In [77]:
df[df['W'] > 0 ][['Y', 'Z']]

Y         Z
A -0.907984 -1.167555
C  1.235684 -1.459479
D  0.712243  0.836411
E  0.753674 -0.845777

In [81]:
df[df['W'] > 0][['Y', 'Z']].loc[['C', 'D']]

Y         Z
C  1.235684 -1.459479
D  0.712243  0.836411

In [82]:
df

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1
B -0.419792  0.723927  1.036089 -1.343167      4
C  1.893363  0.702701  1.235684 -1.459479      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594 -0.743221  0.753674 -0.845777     25

In [83]:
df[df['Y'] < 0]

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1

In [84]:
df[df['W'] > 0]

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1
C  1.893363  0.702701  1.235684 -1.459479      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594 -0.743221  0.753674 -0.845777     25

conditional subsetting

In [88]:
df[(df['W'] > 0) & (df['Y'] < 0)]

# subsetting with conditional
# 1) using symbol
# 2) using bracket

W         X         Y         Z  col_2
A  1.284445 -0.296037 -0.907984 -1.167555      1

In [91]:
df[(df['W'] > 0) | (df['Y'] < 0)][['X', 'Z']].loc[['C', 'D']]

X         Z
C  0.702701 -1.459479
D  0.113500  0.836411

In [92]:
df1

W         X         Y         Z  col_2
A  1.284445       NaN       NaN       NaN      1
B       NaN  0.723927  1.036089       NaN      4
C  1.893363  0.702701  1.235684       NaN      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594       NaN  0.753674       NaN     25

### Handling NaN

In [94]:
df1.isna().sum()

W        1
X        2
Y        1
Z        4
col_2    0
dtype: int64

### Technical Approach

- `.dropna()` ==> menghapus data NaN (baris)
- `.fillna()` ==> membuat/mengisi dengan data sintetis

In [97]:
df1

W         X         Y         Z  col_2
A  1.284445       NaN       NaN       NaN      1
B       NaN  0.723927  1.036089       NaN      4
C  1.893363  0.702701  1.235684       NaN      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594       NaN  0.753674       NaN     25

In [96]:
df1.dropna()

W       X         Y         Z  col_2
D  2.302487  0.1135  0.712243  0.836411     16

In [100]:
df1.fillna(value='empty data')

W           X           Y           Z  col_2
A     1.28444  empty data  empty data  empty data      1
B  empty data    0.723927     1.03609  empty data      4
C     1.89336    0.702701     1.23568  empty data      9
D     2.30249      0.1135    0.712243    0.836411     16
E    0.906594  empty data    0.753674  empty data     25

In [102]:
df1['W'] = df1['W'].fillna(df1['W'].mean())
df1

W         X         Y         Z  col_2
A  1.284445       NaN       NaN       NaN      1
B  1.596722  0.723927  1.036089       NaN      4
C  1.893363  0.702701  1.235684       NaN      9
D  2.302487  0.113500  0.712243  0.836411     16
E  0.906594       NaN  0.753674       NaN     25

# Exploratory Data Analysis (EDA)

In [ ]:
# Exploratory Data Analysis --- EDA
(Harus menguasai Domain/Business Knowledge)

- Pengecekan Tipe Data
- Pengecekan Missing Value - Dan Kita Handling
- Describe Data
- Pengecekan Data Outliers & Kita Handling
- Pengecekan - Extraksi Data datetime/Tanggal jika diperlukan

### Analisa Data
- Univariate (Kolom Tunggal)
- BiVariate / Multivariate (Multi Kolom)
 Ambil Insight - Interpretasi dari Hasil Analisa 
    
Data Visualization
- Univariate
- Bivariate/Multivariate (Multikolom)
Ambil Insight - Interpretasi dari Grafik

-- Kesimpulan & Saran

# Machine Learning
- algorithm
- optimization
- model implementation

In [2]:
# Import default libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##### Handling Outliers ==> DROP or KEEP

1. Kesalahan Input: kesalahan input usia typo 2500 - seharusnya 25 --> DROP

2. 15 - 20 - 10 - 9 - 12 - 250 - 175 - 33 - 12 - 10 - 300 --> formula membuat lele besar, angka besar yang justru dicari. di sini Outliers yang datanya justru dipakai

3. Data Benar: Harga Mobil
    Berdasarkan kebutuhan
    - Analisa Mobil Rakyat ==> mobil premium di Drop
    - Analisa Mobil Premium ==> mobil rakyat di Drop
    - Analisa keduanya ==> 
      - keduanya di KEEP. 
      = Tapi tidak bisa dianalisa bersama, harus dibuat 2 dataframe berbeda
          1. df_rakyat = df[df['harga'] < 1M]
          2. df_rakyat = df[df['harga'] > 1M]

##### Handling Missing Values ==> DROP or FILL
1. DROP:
    - kolom
      
      syarat: 
          - terdapat kolom pengganti:
              - Missing Value ada di kolom jarak (m), kita memiliki kolom jarak (km)
              - Missing Value di Gaji (Rp), kita memiliki Gaji (USD)
          - missing value nya mencapai 70-80%
    - baris
      
      syarat:
          - lihat berapa banyak kolom yang kosong di baris itu
          - pastikan jumlah datanya banyak 
              - data macet: 990, tidak macet: 10 ==> features & target
          - jika ada missing value pada kolom target ==> langsung drop baris
          
2. FILLNA: mengisi data sintetis dengan
    - Harus melihat kolom/features lain
    - Mean ==> data numerik dan tidak ada outliers
    - Median ==> data numerik
    - Modus ==> data kategorikal
    
    
    contoh: jika kolom gaji kosong -> mengisinya harus melihat kolom kota/lokasi dan jabatan

In [116]:
df = pd.read_csv('../data/sample_data.csv', index_col='receipt_id')
df = pd.read_csv('../data/sample_data.csv', index_col=0)
df.head()

receipts_item_id    purchase_time category sub_category  \
receipt_id                                                            
9622257             32369294  7/22/2018 21:19     Rice         Rice   
9446359             31885876  7/15/2018 16:17     Rice         Rice   
9470290             31930241  7/15/2018 12:12     Rice         Rice   
9643416             32418582   7/24/2018 8:27     Rice         Rice   
9692093             32561236  7/26/2018 11:28     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

#### Pengecekan Tipe Data

In [117]:
# Alt 1
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72000 entries, 9622257 to 5808147
Data columns (total 8 columns):
receipts_item_id    72000 non-null int64
purchase_time       72000 non-null object
category            72000 non-null object
sub_category        72000 non-null object
format              72000 non-null object
unit_price          72000 non-null float64
discount            72000 non-null int64
quantity            72000 non-null int64
dtypes: float64(1), int64(3), object(4)
memory usage: 4.9+ MB


#### Cek Missing Value

In [118]:
# Alt 1
df.isnull().sum()

receipts_item_id    0
purchase_time       0
category            0
sub_category        0
format              0
unit_price          0
discount            0
quantity            0
dtype: int64

In [119]:
# Alt 2
df.isna().sum()

receipts_item_id    0
purchase_time       0
category            0
sub_category        0
format              0
unit_price          0
discount            0
quantity            0
dtype: int64

#### Describe Data

In [120]:
df.describe() # descriptive stats untuk tipe data numerik

receipts_item_id     unit_price       discount      quantity
count      7.200000e+04   72000.000000   72000.000000  72000.000000
mean       2.459002e+07   24830.776334     852.195139      1.482861
std        7.169571e+06   24496.419282    4051.061578      1.289382
min        8.904708e+06    2505.000000  -49600.000000      1.000000
25%        1.819982e+07   12500.000000       0.000000      1.000000
50%        2.236586e+07   15472.500000       0.000000      1.000000
75%        3.105228e+07   25100.000000       0.000000      2.000000
max        3.850166e+07  219400.000000  320000.000000     19.000000

In [ ]:
count = jumlah data
mean = rata-rata
std = standar deviasi (sampel)
min = nilai minimum
25% = Q1 = Kuartil 1
50% = Q2 = Kuartil 2 = Median
75% = Q3 = Kuartil 3
max = nilai maximum

##### Describe Data Object

In [121]:
# Alt 1
df.describe(include = np.object)

purchase_time     category sub_category      format
count              72000        72000        72000       72000
unique             62072            3            3           3
top     10/22/2017 12:00  Fabric Care    Detergent  minimarket
freq                  12        36000        36000       46803

In [123]:
# Alt 2
df.describe(include = 'O')

purchase_time     category sub_category      format
count              72000        72000        72000       72000
unique             62072            3            3           3
top     10/22/2017 12:00  Fabric Care    Detergent  minimarket
freq                  12        36000        36000       46803

In [125]:
# Alt 3
df.describe(include = ['object'])

purchase_time     category sub_category      format
count              72000        72000        72000       72000
unique             62072            3            3           3
top     10/22/2017 12:00  Fabric Care    Detergent  minimarket
freq                  12        36000        36000       46803

In [ ]:
count = jumlah data
unique = jumlah unique data
top = data paling sering muncul (modus)
freq = jumlah berapa kali modus muncul

In [127]:
# Alt 4
df.describe(include='all')
df.describe(include='all').T

count unique               top   freq       mean  \
receipts_item_id  72000    NaN               NaN    NaN  2.459e+07   
purchase_time     72000  62072  10/22/2017 12:00     12        NaN   
category          72000      3       Fabric Care  36000        NaN   
sub_category      72000      3         Detergent  36000        NaN   
format            72000      3        minimarket  46803        NaN   
unit_price        72000    NaN               NaN    NaN    24830.8   
discount          72000    NaN               NaN    NaN    852.195   
quantity          72000    NaN               NaN    NaN    1.48286   

                          std          min          25%          50%  \
receipts_item_id  7.16957e+06  8.90471e+06  1.81998e+07  2.23659e+07   
purchase_time             NaN          NaN          NaN          NaN   
category                  NaN          NaN          NaN          NaN   
sub_category              NaN          NaN          NaN          NaN   
format                    NaN          NaN          NaN          NaN   
unit_price            24496.4         2505        12500      15472.5   
discount              4051.06       -49600            0            0   
quantity              1.28938            1            1            1   

                          75%          max  
receipts_item_id  3.10523e+07  3.85017e+07  
purchase_time             NaN          NaN  
category                  NaN          NaN  
sub_category              NaN          NaN  
format                    NaN          NaN  
unit_price              25100       219400  
discount                    0       320000  
quantity                    2           19

#### Pengecekan Outliers
Outliers adalah data di atas Upper Fence atau di bawah Lower Fence

- Upper Fence - Batas Atas = Q3 + (1.5 * IQR)
- Lower Fence - Batas Bawah = Q1 + (1.5 * IQR)

IQR = Q3 - Q1
    
    - Q3 = kuartil 3 = titik tengah antara nilai Median dan nilai Max
    - Q1 = Kuartil 1 = titik tengah antara nilai Median dan nilai Min

In [128]:
df.describe().T

count          mean           std        min          25%  \
receipts_item_id  72000.0  2.459002e+07  7.169571e+06  8904708.0  18199818.75   
unit_price        72000.0  2.483078e+04  2.449642e+04     2505.0     12500.00   
discount          72000.0  8.521951e+02  4.051062e+03   -49600.0         0.00   
quantity          72000.0  1.482861e+00  1.289382e+00        1.0         1.00   

                         50%          75%         max  
receipts_item_id  22365857.0  31052282.25  38501658.0  
unit_price           15472.5     25100.00    219400.0  
discount                 0.0         0.00    320000.0  
quantity                 1.0         2.00        19.0

In [129]:
# mencari Outliers untuk Unit Price
df.describe()['unit_price']

count     72000.000000
mean      24830.776334
std       24496.419282
min        2505.000000
25%       12500.000000
50%       15472.500000
75%       25100.000000
max      219400.000000
Name: unit_price, dtype: float64

In [131]:
Q1 = df.describe()['unit_price']['25%']
Q3 = df.describe()['unit_price']['75%']
IQR = Q3 - Q1

Upper_Fence = Q3 + (1.5 * IQR)
Lower_Fence = Q1 - (1.5 * IQR)

In [132]:
# Data Outliers
df[(df['unit_price'] < Lower_Fence) | (df['unit_price'] > Upper_Fence)]

receipts_item_id     purchase_time              category  \
receipt_id                                                             
9622257             32369294   7/22/2018 21:19                  Rice   
9446359             31885876   7/15/2018 16:17                  Rice   
9470290             31930241   7/15/2018 12:12                  Rice   
9643416             32418582    7/24/2018 8:27                  Rice   
9692093             32561236   7/26/2018 11:28                  Rice   
...                      ...               ...                   ...   
5965798             18136614  12/31/2017 17:50  Sugar/Flavored Syrup   
5742503             17449270  12/12/2017 15:57  Sugar/Flavored Syrup   
5648387             17146348  12/06/2017 14:14  Sugar/Flavored Syrup   
5763026             17508220  12/14/2017 17:29  Sugar/Flavored Syrup   
5906213             17966261  12/26/2017 17:05  Sugar/Flavored Syrup   

           sub_category       format  unit_price  discount  quantity  
receipt_id                                                            
9622257            Rice  supermarket    128000.0         0         1  
9446359            Rice   minimarket    102750.0         0         1  
9470290            Rice  supermarket     64000.0         0         3  
9643416            Rice   minimarket     65000.0         0         1  
9692093            Rice  supermarket    124500.0         0         1  
...                 ...          ...         ...       ...       ...  
5965798           Sugar  hypermarket     55130.0         0         1  
5742503           Sugar  hypermarket     59900.0         0         2  
5648387           Sugar  supermarket     48600.0         0         1  
5763026           Sugar  supermarket     59950.0         0         1  
5906213           Sugar  supermarket     56465.0         0         1  

[11388 rows x 8 columns]

In [145]:
df.head()

receipts_item_id    purchase_time category sub_category  \
receipt_id                                                            
9622257             32369294  7/22/2018 21:19     Rice         Rice   
9446359             31885876  7/15/2018 16:17     Rice         Rice   
9470290             31930241  7/15/2018 12:12     Rice         Rice   
9643416             32418582   7/24/2018 8:27     Rice         Rice   
9692093             32561236  7/26/2018 11:28     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

In [134]:
df['category'].unique()

array(['Rice', 'Fabric Care', 'Sugar/Flavored Syrup'], dtype=object)

In [135]:
df['category'].nunique()

3

In [136]:
df['category'].dtypes

dtype('O')

In [137]:
df['category'].isna().sum()

0

In [139]:
round((((df['category'].isna().sum()) / len(df)) * 100), 2)

0.0

In [140]:
df['category'].drop_duplicates().sample(2).values

array(['Rice', 'Sugar/Flavored Syrup'], dtype=object)

In [141]:
df.columns

Index(['receipts_item_id', 'purchase_time', 'category', 'sub_category',
       'format', 'unit_price', 'discount', 'quantity'],
      dtype='object')

In [148]:
dataDesc = []

for i in df.columns:
    dataDesc.append([
        i,
        df[i].dtypes,
        df[i].isna().sum(),
        round((((df[i].isna().sum()) / len(df)) * 100), 2),
        df[i].nunique(),
        df[i].drop_duplicates().sample(2).values
    ])

In [149]:
pd.DataFrame(dataDesc, columns=[
    'Data Feature',
    'Data Types',
    'Null',
    'Null Percentage',
    'Unique',
    'Unique Sample'
])

Data Feature Data Types  Null  Null Percentage  Unique  \
0  receipts_item_id      int64     0              0.0   72000   
1     purchase_time     object     0              0.0   62072   
2          category     object     0              0.0       3   
3      sub_category     object     0              0.0       3   
4            format     object     0              0.0       3   
5        unit_price    float64     0              0.0    3884   
6          discount      int64     0              0.0    1329   
7          quantity      int64     0              0.0      19   

                        Unique Sample  
0                [32329845, 16070893]  
1  [7/18/2018 7:58, 12/08/2017 19:20]  
2                 [Rice, Fabric Care]  
3                       [Rice, Sugar]  
4           [hypermarket, minimarket]  
5                  [21525.0, 94490.0]  
6                      [15160, 29560]  
7                            [18, 13]

#### Proses konversi tanggal
Jika kolom tanggal bertipe object, harus dikonversi menjadi datetime

In [ ]:
# Alt 1
Menggunakan `parse_dates = [nama kolom]` ketika di awal membaca file

In [151]:
df = pd.read_csv('../data/sample_data.csv', index_col=0, parse_dates=['purchase_time'])
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

In [152]:
df.dtypes

receipts_item_id             int64
purchase_time       datetime64[ns]
category                    object
sub_category                object
format                      object
unit_price                 float64
discount                     int64
quantity                     int64
dtype: object

In [ ]:
# Alt 2
- menggunakan fungsi `.astype('datetime64')`
- astype digunakan untuk mengubah tipe data, tidak terbatas pada tanggal

In [154]:
df = pd.read_csv('../data/sample_data.csv', index_col=0)
df.head()

receipts_item_id    purchase_time category sub_category  \
receipt_id                                                            
9622257             32369294  7/22/2018 21:19     Rice         Rice   
9446359             31885876  7/15/2018 16:17     Rice         Rice   
9470290             31930241  7/15/2018 12:12     Rice         Rice   
9643416             32418582   7/24/2018 8:27     Rice         Rice   
9692093             32561236  7/26/2018 11:28     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

In [155]:
df.dtypes

receipts_item_id      int64
purchase_time        object
category             object
sub_category         object
format               object
unit_price          float64
discount              int64
quantity              int64
dtype: object

In [156]:
df['purchase_time'] = df['purchase_time'].astype('datetime64')
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

In [158]:
df.dtypes

receipts_item_id             int64
purchase_time       datetime64[ns]
category                    object
sub_category                object
format                      object
unit_price                 float64
discount                     int64
quantity                     int64
dtype: object

In [ ]:
# Alt 3
- menggunakan fungsi to_datetime('nama kolom')

In [7]:
df = pd.read_csv('data/sample_data.csv', index_col=0)
df.head()

receipts_item_id    purchase_time category sub_category  \
receipt_id                                                            
9622257             32369294  7/22/2018 21:19     Rice         Rice   
9446359             31885876  7/15/2018 16:17     Rice         Rice   
9470290             31930241  7/15/2018 12:12     Rice         Rice   
9643416             32418582   7/24/2018 8:27     Rice         Rice   
9692093             32561236  7/26/2018 11:28     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

In [8]:
df['purchase_time'] = pd.to_datetime(df['purchase_time'])
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

#### Proses konversi tanggal yang tidak sama

In [3]:
date = pd.Series([
    '01-maret-2020',
    'july/17/2019',
    'Agustus-20-2021',
    '16-Agustus-2020',
    '20/may/2017',
    '2021/01/29'
])
date

0      01-maret-2020
1       july/17/2019
2    Agustus-20-2021
3    16-Agustus-2020
4        20/may/2017
5         2021/01/29
dtype: object

In [4]:
import dateparser

In [5]:
date.apply(dateparser.parse)

0   2020-03-01
1   2019-07-17
2   2021-08-20
3   2020-08-16
4   2017-05-20
5   2021-01-29
dtype: datetime64[ns]

In [9]:
df['purchase_time'] = df['purchase_time'].apply(dateparser.parse)

TypeError: Input type must be str

####  Proses Ekstraksi Tanggal
https://strftime.org/

In [12]:
purchase_dt = df['purchase_time'].dt

In [13]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity  
receipt_id                                               
9622257     supermarket    128000.0         0         1  
9446359      minimarket    102750.0         0         1  
9470290     supermarket     64000.0         0         3  
9643416      minimarket     65000.0         0         1  
9692093     supermarket    124500.0         0         1

In [14]:
# ambil data bulan
purchase_dt.month.head()

receipt_id
9622257    7
9446359    7
9470290    7
9643416    7
9692093    7
Name: purchase_time, dtype: int64

In [15]:
purchase_dt.month_name().head()

receipt_id
9622257    July
9446359    July
9470290    July
9643416    July
9692093    July
Name: purchase_time, dtype: object

In [16]:
purchase_dt.year.head()

receipt_id
9622257    2018
9446359    2018
9470290    2018
9643416    2018
9692093    2018
Name: purchase_time, dtype: int64

In [17]:
df['month'] = purchase_dt.month_name()

In [18]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  
receipt_id                                                     
9622257     supermarket    128000.0         0         1  July  
9446359      minimarket    102750.0         0         1  July  
9470290     supermarket     64000.0         0         3  July  
9643416      minimarket     65000.0         0         1  July  
9692093     supermarket    124500.0         0         1  July

In [19]:
df['year'] = purchase_dt.year

In [20]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year  
receipt_id                                                           
9622257     supermarket    128000.0         0         1  July  2018  
9446359      minimarket    102750.0         0         1  July  2018  
9470290     supermarket     64000.0         0         3  July  2018  
9643416      minimarket     65000.0         0         1  July  2018  
9692093     supermarket    124500.0         0         1  July  2018

In [21]:
purchase_dt.day.head() ## ekstraksi tanggal

receipt_id
9622257    22
9446359    15
9470290    15
9643416    24
9692093    26
Name: purchase_time, dtype: int64

In [22]:
purchase_dt.dayofweek.head() ## ekstraksi urutan hari dalam seminggu 0 = senin

receipt_id
9622257    6
9446359    6
9470290    6
9643416    1
9692093    3
Name: purchase_time, dtype: int64

In [23]:
purchase_dt.hour.head()

receipt_id
9622257    21
9446359    16
9470290    12
9643416     8
9692093    11
Name: purchase_time, dtype: int64

In [24]:
purchase_dt.day_name().head()

receipt_id
9622257      Sunday
9446359      Sunday
9470290      Sunday
9643416     Tuesday
9692093    Thursday
Name: purchase_time, dtype: object

In [25]:
df['day'] = purchase_dt.day_name()

In [26]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  
receipt_id                                                                     
9622257     supermarket    128000.0         0         1  July  2018    Sunday  
9446359      minimarket    102750.0         0         1  July  2018    Sunday  
9470290     supermarket     64000.0         0         3  July  2018    Sunday  
9643416      minimarket     65000.0         0         1  July  2018   Tuesday  
9692093     supermarket    124500.0         0         1  July  2018  Thursday

In [27]:
purchase_dt.to_period('D').head()

receipt_id
9622257    2018-07-22
9446359    2018-07-15
9470290    2018-07-15
9643416    2018-07-24
9692093    2018-07-26
Name: purchase_time, dtype: period[D]

In [28]:
purchase_dt.to_period('M').head()

receipt_id
9622257    2018-07
9446359    2018-07
9470290    2018-07
9643416    2018-07
9692093    2018-07
Name: purchase_time, dtype: period[M]

In [29]:
# membandingkan per minggu nya
purchase_dt.to_period('W').head()

receipt_id
9622257    2018-07-16/2018-07-22
9446359    2018-07-09/2018-07-15
9470290    2018-07-09/2018-07-15
9643416    2018-07-23/2018-07-29
9692093    2018-07-23/2018-07-29
Name: purchase_time, dtype: period[W-SUN]

In [30]:
purchase_dt.to_period('Q').head()

receipt_id
9622257    2018Q3
9446359    2018Q3
9470290    2018Q3
9643416    2018Q3
9692093    2018Q3
Name: purchase_time, dtype: period[Q-DEC]

In [31]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  
receipt_id                                                                     
9622257     supermarket    128000.0         0         1  July  2018    Sunday  
9446359      minimarket    102750.0         0         1  July  2018    Sunday  
9470290     supermarket     64000.0         0         3  July  2018    Sunday  
9643416      minimarket     65000.0         0         1  July  2018   Tuesday  
9692093     supermarket    124500.0         0         1  July  2018  Thursday

In [32]:
df['quarter'] = purchase_dt.to_period('Q')
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  \
receipt_id                                                                      
9622257     supermarket    128000.0         0         1  July  2018    Sunday   
9446359      minimarket    102750.0         0         1  July  2018    Sunday   
9470290     supermarket     64000.0         0         3  July  2018    Sunday   
9643416      minimarket     65000.0         0         1  July  2018   Tuesday   
9692093     supermarket    124500.0         0         1  July  2018  Thursday   

           quarter  
receipt_id          
9622257     2018Q3  
9446359     2018Q3  
9470290     2018Q3  
9643416     2018Q3  
9692093     2018Q3

In [33]:
df.sample(5)

receipts_item_id       purchase_time              category  \
receipt_id                                                               
11346463            37888801 2018-09-29 17:13:00           Fabric Care   
5405208             16389738 2017-11-12 19:10:00           Fabric Care   
8741641             29853857 2018-06-10 12:50:00           Fabric Care   
5520146             16761647 2017-11-25 16:14:00           Fabric Care   
6923095             20926018 2018-03-09 01:32:00  Sugar/Flavored Syrup   

           sub_category       format  unit_price  discount  quantity  \
receipt_id                                                             
11346463      Detergent   minimarket     18000.0         0         1   
5405208       Detergent   minimarket     15900.0      6800         2   
8741641       Detergent  hypermarket     13500.0      1400         2   
5520146       Detergent   minimarket     26000.0         0         1   
6923095           Sugar   minimarket     17800.0         0         1   

                month  year       day quarter  
receipt_id                                     
11346463    September  2018  Saturday  2018Q3  
5405208      November  2017    Sunday  2017Q4  
8741641          June  2018    Sunday  2018Q2  
5520146      November  2017  Saturday  2017Q4  
6923095         March  2018    Friday  2018Q1

In [34]:
df['Total'] = df['quantity'] * df['unit_price']
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  \
receipt_id                                                                      
9622257     supermarket    128000.0         0         1  July  2018    Sunday   
9446359      minimarket    102750.0         0         1  July  2018    Sunday   
9470290     supermarket     64000.0         0         3  July  2018    Sunday   
9643416      minimarket     65000.0         0         1  July  2018   Tuesday   
9692093     supermarket    124500.0         0         1  July  2018  Thursday   

           quarter     Total  
receipt_id                    
9622257     2018Q3  128000.0  
9446359     2018Q3  102750.0  
9470290     2018Q3  192000.0  
9643416     2018Q3   65000.0  
9692093     2018Q3  124500.0

In [36]:
df['custom'] = purchase_dt.strftime('%B - %H : %H')
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  \
receipt_id                                                                      
9622257     supermarket    128000.0         0         1  July  2018    Sunday   
9446359      minimarket    102750.0         0         1  July  2018    Sunday   
9470290     supermarket     64000.0         0         3  July  2018    Sunday   
9643416      minimarket     65000.0         0         1  July  2018   Tuesday   
9692093     supermarket    124500.0         0         1  July  2018  Thursday   

           quarter     Total          custom  
receipt_id                                    
9622257     2018Q3  128000.0  July - 21 : 21  
9446359     2018Q3  102750.0  July - 16 : 16  
9470290     2018Q3  192000.0  July - 12 : 12  
9643416     2018Q3   65000.0  July - 08 : 08  
9692093     2018Q3  124500.0  July - 11 : 11

Analisa Data
- Group by ==> Adopt dari SQL
- Pivot table ==> Adopt dari Ms. Excell
- Crosstab ==> Original Pandas

##### 1) crosstab
Analisa Univariate ==> Analisa 1 kolom

In [37]:
df['category'].value_counts()

Fabric Care             36000
Sugar/Flavored Syrup    24000
Rice                    12000
Name: category, dtype: int64

In [38]:
pd.crosstab(df['category'], columns='count')

col_0                 count
category                   
Fabric Care           36000
Rice                  12000
Sugar/Flavored Syrup  24000

In [39]:
pd.crosstab(df['format'], columns='count') # alt 1

col_0        count
format            
hypermarket   5371
minimarket   46803
supermarket  19826

In [42]:
pd.crosstab(index=df['category'], columns='count') # alt 2

col_0                 count
category                   
Fabric Care           36000
Rice                  12000
Sugar/Flavored Syrup  24000

In [40]:
# contoh insight ==> penjualan tertinggi ada di minimarket dan terendah di hypermart,
# sehingga jika akan melakukan promo, sebaiknya dilakukan di minimarket

In [41]:
# Fungsi aggregation default pada crosstab menggunakan COUNT, sehingga bisa dilakukan tanpa data numerik
# Ketika melakukan analisa univariate menggunakan crosstab untuk kolom kategorikal, menghasilkan output yang sama dengan fungsi value_counts()
# Fungsi value_counts() menghasilkan tipe data Series, crosstab menghasilkan Dataframe

Analisa Multivariate ==> Analisa 2 atau lebih kolom

In [45]:
# 2 columns
pd.crosstab(index=df['sub_category'], columns=df['format']) # default isi nya adalah count/jumlah data

format        hypermarket  minimarket  supermarket
sub_category                                      
Detergent            2611       24345         9044
Rice                  999        7088         3913
Sugar                1761       15370         6869

In [46]:
# 2 columns
pd.crosstab(index=df['sub_category'], columns=df['day'])

day           Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
sub_category                                                                
Detergent       5748    4337      6147    6381      4320     4522       4545
Rice            1646    1551      1915    2234      1552     1621       1481
Sugar           3384    3162      3766    3958      3266     3284       3180

In [49]:
# 2 columns
pd.crosstab(index=df['day'], columns=df['sub_category'])

sub_category  Detergent  Rice  Sugar
day                                 
Friday             5748  1646   3384
Monday             4337  1551   3162
Saturday           6147  1915   3766
Sunday             6381  2234   3958
Thursday           4320  1552   3266
Tuesday            4522  1621   3284
Wednesday          4545  1481   3180

In [50]:
# more than 2 columns
pd.crosstab(index=[df['sub_category'], df['format']], columns=df['day'])

day                       Friday  Monday  Saturday  Sunday  Thursday  Tuesday  \
sub_category format                                                             
Detergent    hypermarket     398     264       538     598       266      291   
             minimarket     3884    3003      4000    4097      3027     3108   
             supermarket    1466    1070      1609    1686      1027     1123   
Rice         hypermarket     154     111       175     263       100       94   
             minimarket      973     958      1100    1210       902     1011   
             supermarket     519     482       640     761       550      516   
Sugar        hypermarket     250     198       303     374       205      215   
             minimarket     2147    2083      2311    2390      2204     2150   
             supermarket     987     881      1152    1194       857      919   

day                       Wednesday  
sub_category format                  
Detergent    hypermarket        256  
             minimarket        3226  
             supermarket       1063  
Rice         hypermarket        102  
             minimarket         934  
             supermarket        445  
Sugar        hypermarket        216  
             minimarket        2085  
             supermarket        879

In [51]:
# more than 2 columns
pd.crosstab(index=[df['format'], df['sub_category']], columns=df['day'])

day                       Friday  Monday  Saturday  Sunday  Thursday  Tuesday  \
format      sub_category                                                        
hypermarket Detergent        398     264       538     598       266      291   
            Rice             154     111       175     263       100       94   
            Sugar            250     198       303     374       205      215   
minimarket  Detergent       3884    3003      4000    4097      3027     3108   
            Rice             973     958      1100    1210       902     1011   
            Sugar           2147    2083      2311    2390      2204     2150   
supermarket Detergent       1466    1070      1609    1686      1027     1123   
            Rice             519     482       640     761       550      516   
            Sugar            987     881      1152    1194       857      919   

day                       Wednesday  
format      sub_category             
hypermarket Detergent           256  
            Rice                102  
            Sugar               216  
minimarket  Detergent          3226  
            Rice                934  
            Sugar              2085  
supermarket Detergent          1063  
            Rice                445  
            Sugar               879

In [54]:
# more than 2 columns
pd.crosstab(index=df['day'], columns=[df['format'], df['sub_category']])

format       hypermarket            minimarket             supermarket       \
sub_category   Detergent Rice Sugar  Detergent  Rice Sugar   Detergent Rice   
day                                                                           
Friday               398  154   250       3884   973  2147        1466  519   
Monday               264  111   198       3003   958  2083        1070  482   
Saturday             538  175   303       4000  1100  2311        1609  640   
Sunday               598  263   374       4097  1210  2390        1686  761   
Thursday             266  100   205       3027   902  2204        1027  550   
Tuesday              291   94   215       3108  1011  2150        1123  516   
Wednesday            256  102   216       3226   934  2085        1063  445   

format              
sub_category Sugar  
day                 
Friday         987  
Monday         881  
Saturday      1152  
Sunday        1194  
Thursday       857  
Tuesday        919  
Wednesday      879

In [55]:
# more than 2 columns
pd.crosstab(index=[df['year'], df['day']], columns=[df['format'], df['sub_category']])

format         hypermarket            minimarket            supermarket       \
sub_category     Detergent Rice Sugar  Detergent Rice Sugar   Detergent Rice   
year day                                                                       
2017 Friday            109   32    75        955  245   530         336  133   
     Monday             59   20    50        733  233   510         266  114   
     Saturday          128   42    76       1041  280   531         362  187   
     Sunday            152   71   100       1098  355   641         436  211   
     Thursday           57   19    49        754  225   517         275  127   
     Tuesday            69   20    54        765  221   545         267  131   
     Wednesday          63   21    49        843  205   522         232  108   
2018 Friday            289  122   175       2929  728  1617        1130  386   
     Monday            205   91   148       2270  725  1573         804  368   
     Saturday          410  133   227       2959  820  1780        1247  453   
     Sunday            446  192   274       2999  855  1749        1250  550   
     Thursday          209   81   156       2273  677  1687         752  423   
     Tuesday           222   74   161       2343  790  1605         856  385   
     Wednesday         193   81   167       2383  729  1563         831  337   

format                
sub_category   Sugar  
year day              
2017 Friday      225  
     Monday      213  
     Saturday    276  
     Sunday      304  
     Thursday    238  
     Tuesday     255  
     Wednesday   240  
2018 Friday      762  
     Monday      668  
     Saturday    876  
     Sunday      890  
     Thursday    619  
     Tuesday     664  
     Wednesday   639

In [57]:
pd.crosstab(index=[df['format'], df['sub_category'], df['day']], columns='count')

col_0                               count
format      sub_category day             
hypermarket Detergent    Friday       398
                         Monday       264
                         Saturday     538
                         Sunday       598
                         Thursday     266
...                                   ...
supermarket Sugar        Saturday    1152
                         Sunday      1194
                         Thursday     857
                         Tuesday      919
                         Wednesday    879

[63 rows x 1 columns]

In [ ]:
# if you torture the data long enough, it will confess

normalize

In [58]:
(pd.crosstab(index=df['format'], columns=df['sub_category'], normalize=True) * 100).round(2)

sub_category  Detergent  Rice  Sugar
format                              
hypermarket        3.63  1.39   2.45
minimarket        33.81  9.84  21.35
supermarket       12.56  5.43   9.54

In [59]:
(pd.crosstab(index=df['format'], columns=df['sub_category'], normalize='all') * 100).round(2)
# normalize True dan all --> fokus di keseluruhan

sub_category  Detergent  Rice  Sugar
format                              
hypermarket        3.63  1.39   2.45
minimarket        33.81  9.84  21.35
supermarket       12.56  5.43   9.54

In [62]:
(pd.crosstab(index=df['format'], columns=df['sub_category'], normalize='index') * 100)
# normalize True dan index --> fokus di index

sub_category  Detergent       Rice      Sugar
format                                       
hypermarket   48.612921  18.599888  32.787190
minimarket    52.015896  15.144328  32.839775
supermarket   45.616867  19.736709  34.646424

In [61]:
(pd.crosstab(index=df['format'], columns=df['sub_category'], normalize='columns') * 100).round(2)
# normalize True dan index --> fokus di column

sub_category  Detergent   Rice  Sugar
format                               
hypermarket        7.25   8.33   7.34
minimarket        67.62  59.07  64.04
supermarket       25.12  32.61  28.62

In [65]:
pd.crosstab(index=df['format'], columns=df['sub_category'], margins=True, normalize='all') * 100

sub_category  Detergent       Rice      Sugar         All
format                                                   
hypermarket    3.626389   1.387500   2.445833    7.459722
minimarket    33.812500   9.844444  21.347222   65.004167
supermarket   12.561111   5.434722   9.540278   27.536111
All           50.000000  16.666667  33.333333  100.000000

In [66]:
pd.crosstab(index=df['format'], columns=df['sub_category'], margins=True, normalize='index') * 100

sub_category  Detergent       Rice      Sugar
format                                       
hypermarket   48.612921  18.599888  32.787190
minimarket    52.015896  15.144328  32.839775
supermarket   45.616867  19.736709  34.646424
All           50.000000  16.666667  33.333333

In [68]:
pd.crosstab(index=df['format'], columns=df['sub_category'], margins=True, normalize='columns') * 100

sub_category  Detergent       Rice      Sugar        All
format                                                  
hypermarket    7.252778   8.325000   7.337500   7.459722
minimarket    67.625000  59.066667  64.041667  65.004167
supermarket   25.122222  32.608333  28.620833  27.536111

In [ ]:
transaksi di minimarket 65%

#### Aggregate Function - Dataframe
- Menggunakan minimal satu kolom yang bertipe numerik
- kolom tersebut akan dikombinasikan dengan kolom kategorik

==> Syarat
- parameter `values` HARUS DIISI ==> berisi kolom numerik
- parameter `aggfunc` HARUS DIISI ==> berisi aggregate function yg akan digunakan

In [69]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  \
receipt_id                                                                      
9622257     supermarket    128000.0         0         1  July  2018    Sunday   
9446359      minimarket    102750.0         0         1  July  2018    Sunday   
9470290     supermarket     64000.0         0         3  July  2018    Sunday   
9643416      minimarket     65000.0         0         1  July  2018   Tuesday   
9692093     supermarket    124500.0         0         1  July  2018  Thursday   

           quarter     Total          custom  
receipt_id                                    
9622257     2018Q3  128000.0  July - 21 : 21  
9446359     2018Q3  102750.0  July - 16 : 16  
9470290     2018Q3  192000.0  July - 12 : 12  
9643416     2018Q3   65000.0  July - 08 : 08  
9692093     2018Q3  124500.0  July - 11 : 11

In [72]:
pd.crosstab(index=df['sub_category'], columns='avg price', values=df['unit_price'], aggfunc='mean').round(2)

col_0         avg price
sub_category           
Detergent      17893.79
Rice           70013.15
Sugar          12645.07

In [73]:
pd.crosstab(index=df['format'], columns=df['sub_category'], values=df['unit_price'], aggfunc='mean').round(2)

sub_category  Detergent      Rice     Sugar
format                                     
hypermarket    19328.14  71205.46  13539.92
minimarket     17757.14  67135.57  12352.14
supermarket    17847.56  74921.18  13071.11

In [74]:
pd.crosstab(index=df['format'], columns=df['sub_category'], values=df['unit_price'], aggfunc='max').round(2)

sub_category  Detergent      Rice    Sugar
format                                    
hypermarket     59500.0  214000.0  59950.0
minimarket      59000.0  219400.0  59900.0
supermarket     59900.0  219000.0  59950.0

In [75]:
pd.crosstab(index=df['format'], columns=df['sub_category'], values=df['unit_price'], aggfunc=('mean', 'max', 'min')).round(2)

max                         mean                      \
sub_category Detergent      Rice    Sugar Detergent      Rice     Sugar   
format                                                                    
hypermarket    59500.0  214000.0  59950.0  19328.14  71205.46  13539.92   
minimarket     59000.0  219400.0  59900.0  17757.14  67135.57  12352.14   
supermarket    59900.0  219000.0  59950.0  17847.56  74921.18  13071.11   

                   min                   
sub_category Detergent     Rice   Sugar  
format                                   
hypermarket     2600.0  10329.0  5000.0  
minimarket      2505.0   9400.0  5000.0  
supermarket     2510.0   9395.0  5000.0

In [76]:
pd.crosstab(index=[df['sub_category'], df['format']], columns=df['day'], values=df['unit_price'], aggfunc=('mean', 'max', min)).round(2)

max                                          \
day                         Friday    Monday  Saturday    Sunday  Thursday   
sub_category format                                                          
Detergent    hypermarket   55440.0   57000.0   58470.0   55560.0   54475.0   
             minimarket    56000.0   57000.0   58000.0   57100.0   57500.0   
             supermarket   57200.0   53200.0   56400.0   59600.0   55000.0   
Rice         hypermarket  141200.0  175000.0  195650.0  129000.0  128000.0   
             minimarket   215000.0  219400.0  215000.0  219000.0  215000.0   
             supermarket  218900.0  219000.0  214000.0  218000.0  192000.0   
Sugar        hypermarket   43815.0   59950.0   59500.0   59900.0   49600.0   
             minimarket    47200.0   57000.0   56000.0   58000.0   59900.0   
             supermarket   58500.0   59500.0   59900.0   59900.0   59950.0   

                                                  mean                      \
day                        Tuesday Wednesday    Friday    Monday  Saturday   
sub_category format                                                          
Detergent    hypermarket   59500.0   50000.0  18891.04  19138.56  19970.34   
             minimarket    59000.0   55675.0  17694.00  17560.32  17747.66   
             supermarket   59900.0   53900.0  17535.59  18133.63  17773.89   
Rice         hypermarket  213725.0  214000.0  73596.73  66298.69  72381.89   
             minimarket   215000.0  218592.0  65973.96  68546.85  66611.12   
             supermarket  179900.0  192000.0  77468.79  73603.42  74740.14   
Sugar        hypermarket   59900.0   50000.0  12885.25  13358.89  13939.89   
             minimarket    50000.0   57000.0  12249.18  12457.94  12313.93   
             supermarket   59216.0   59900.0  12982.34  13024.60  13001.97   

                          ...                                    min           \
day                       ...  Thursday   Tuesday Wednesday   Friday   Monday   
sub_category format       ...                                                   
Detergent    hypermarket  ...  19879.21  19389.39  19372.11   2800.0   2600.0   
             minimarket   ...  17987.28  17901.03  17809.98   2600.0   2575.0   
             supermarket  ...  17906.23  17944.18  17797.29   2510.0   2510.0   
Rice         hypermarket  ...  68319.88  74470.87  68216.51  10948.0  10329.0   
             minimarket   ...  67578.55  68448.32  66220.13   9500.0   9400.0   
             supermarket  ...  75706.44  73134.50  71961.80   9990.0   9450.0   
Sugar        hypermarket  ...  13324.35  13794.59  13234.43   5250.0   5000.0   
             minimarket   ...  12511.78  12286.60  12255.60   5000.0   5000.0   
             supermarket  ...  12694.99  13436.08  13234.81   5100.0   5198.0   

                                                                        
day                      Saturday   Sunday Thursday  Tuesday Wednesday  
sub_category format                                                     
Detergent    hypermarket   2800.0   2800.0   2600.0   3185.0    2900.0  
             minimarket    2540.0   2505.0   2550.0   2600.0    2550.0  
             supermarket   2565.0   2525.0   2540.0   2515.0    2565.0  
Rice         hypermarket  11500.0  10900.0  12000.0  12234.0   11900.0  
             minimarket    9800.0   9500.0   9500.0   9900.0   10100.0  
             supermarket   9500.0   9395.0   9400.0   9400.0    9485.0  
Sugar        hypermarket   5890.0   5890.0   5200.0   5890.0    5950.0  
             minimarket    5000.0   5000.0   5000.0   5150.0    5000.0  
             supermarket   5000.0   5000.0   5000.0   5500.0    5250.0  

[9 rows x 21 columns]

In [79]:
pd.crosstab(index=df['day'], columns=[df['sub_category'], df['format']], margins=True)

sub_category   Detergent                               Rice             \
format       hypermarket minimarket supermarket hypermarket minimarket   
day                                                                      
Friday               398       3884        1466         154        973   
Monday               264       3003        1070         111        958   
Saturday             538       4000        1609         175       1100   
Sunday               598       4097        1686         263       1210   
Thursday             266       3027        1027         100        902   
Tuesday              291       3108        1123          94       1011   
Wednesday            256       3226        1063         102        934   
All                 2611      24345        9044         999       7088   

sub_category                   Sugar                           All  
format       supermarket hypermarket minimarket supermarket         
day                                                                 
Friday               519         250       2147         987  10778  
Monday               482         198       2083         881   9050  
Saturday             640         303       2311        1152  11828  
Sunday               761         374       2390        1194  12573  
Thursday             550         205       2204         857   9138  
Tuesday              516         215       2150         919   9427  
Wednesday            445         216       2085         879   9206  
All                 3913        1761      15370        6869  72000

In [83]:
pd.crosstab(index=df['day'], columns=[df['sub_category'], df['format']], values=df['unit_price'], aggfunc=('median')).round(2)

sub_category   Detergent                               Rice             \
format       hypermarket minimarket supermarket hypermarket minimarket   
day                                                                      
Friday           16312.5    16800.0     16190.0     64000.0    62500.0   
Monday           16952.5    16800.0     16890.0     64000.0    63500.0   
Saturday         16972.5    16800.0     16375.0     64000.0    62500.0   
Sunday           16700.0    16800.0     16600.0     64000.0    62500.0   
Thursday         16995.0    16800.0     16200.0     64000.0    63500.0   
Tuesday          16950.0    16800.0     16900.0     64000.0    63500.0   
Wednesday        17450.0    16800.0     16700.0     64000.0    62900.0   

sub_category                   Sugar                         
format       supermarket hypermarket minimarket supermarket  
day                                                          
Friday           64000.0    12000.00    12500.0     12400.0  
Monday           64000.0    12273.46    12500.0     12400.0  
Saturday         64000.0    12300.00    12500.0     12400.0  
Sunday           64000.0    12300.00    12500.0     12400.0  
Thursday         64000.0    12000.00    12500.0     12400.0  
Tuesday          64000.0    12300.00    12500.0     12400.0  
Wednesday        64000.0    12300.00    12500.0     12400.0

##### 2) pivot table

In [82]:
pd.pivot_table(data=df, index='day', columns=['sub_category', 'format'], values='unit_price', aggfunc='median')

sub_category   Detergent                               Rice             \
format       hypermarket minimarket supermarket hypermarket minimarket   
day                                                                      
Friday           16312.5    16800.0     16190.0     64000.0    62500.0   
Monday           16952.5    16800.0     16890.0     64000.0    63500.0   
Saturday         16972.5    16800.0     16375.0     64000.0    62500.0   
Sunday           16700.0    16800.0     16600.0     64000.0    62500.0   
Thursday         16995.0    16800.0     16200.0     64000.0    63500.0   
Tuesday          16950.0    16800.0     16900.0     64000.0    63500.0   
Wednesday        17450.0    16800.0     16700.0     64000.0    62900.0   

sub_category                   Sugar                         
format       supermarket hypermarket minimarket supermarket  
day                                                          
Friday           64000.0   12000.000    12500.0     12400.0  
Monday           64000.0   12273.465    12500.0     12400.0  
Saturday         64000.0   12300.000    12500.0     12400.0  
Sunday           64000.0   12300.000    12500.0     12400.0  
Thursday         64000.0   12000.000    12500.0     12400.0  
Tuesday          64000.0   12300.000    12500.0     12400.0  
Wednesday        64000.0   12300.000    12500.0     12400.0

In [87]:
# subsetting combined with pivot table
df[df['unit_price'] > 10000].pivot_table(index='day', columns=['sub_category', 'format'], values='unit_price', aggfunc='median')

sub_category   Detergent                               Rice             \
format       hypermarket minimarket supermarket hypermarket minimarket   
day                                                                      
Friday           16900.0    17200.0     17096.0     64000.0    62500.0   
Monday           17500.0    17300.0     17490.0     64000.0    63500.0   
Saturday         17875.0    17500.0     17190.0     64000.0    62500.0   
Sunday           16990.0    17200.0     17290.0     64000.0    62900.0   
Thursday         17400.0    17500.0     17290.0     64000.0    63500.0   
Tuesday          17800.0    17500.0     17600.0     64000.0    63500.0   
Wednesday        18050.0    17400.0     17350.0     64000.0    62900.0   

sub_category                   Sugar                         
format       supermarket hypermarket minimarket supermarket  
day                                                          
Friday           64000.0     12200.0    12500.0     12400.0  
Monday           64000.0     12300.0    12500.0     12400.0  
Saturday         64000.0     12300.0    12500.0     12400.0  
Sunday           64000.0     12300.0    12500.0     12400.0  
Thursday         64000.0     12300.0    12500.0     12400.0  
Tuesday          64000.0     12362.5    12500.0     12400.0  
Wednesday        64000.0     12300.0    12500.0     12400.0

In [88]:
# subsetting combined with crosstab
df2 = df[df['unit_price'] > 10000]
pd.crosstab(index=df2['day'], columns=[df2['sub_category'], df2['format']], values=df2['unit_price'], aggfunc=('median')).round(2)

sub_category   Detergent                               Rice             \
format       hypermarket minimarket supermarket hypermarket minimarket   
day                                                                      
Friday           16900.0    17200.0     17096.0     64000.0    62500.0   
Monday           17500.0    17300.0     17490.0     64000.0    63500.0   
Saturday         17875.0    17500.0     17190.0     64000.0    62500.0   
Sunday           16990.0    17200.0     17290.0     64000.0    62900.0   
Thursday         17400.0    17500.0     17290.0     64000.0    63500.0   
Tuesday          17800.0    17500.0     17600.0     64000.0    63500.0   
Wednesday        18050.0    17400.0     17350.0     64000.0    62900.0   

sub_category                   Sugar                         
format       supermarket hypermarket minimarket supermarket  
day                                                          
Friday           64000.0     12200.0    12500.0     12400.0  
Monday           64000.0     12300.0    12500.0     12400.0  
Saturday         64000.0     12300.0    12500.0     12400.0  
Sunday           64000.0     12300.0    12500.0     12400.0  
Thursday         64000.0     12300.0    12500.0     12400.0  
Tuesday          64000.0     12362.5    12500.0     12400.0  
Wednesday        64000.0     12300.0    12500.0     12400.0

Perbedaan Crosstab dan Pivot Table
- crosstab tidak memiliki parameter data, sehingga tidak bisa melakukan subsetting/filtering langsung seperti pivot table
- pada pivot table, fungsi aggregate DEFAULT nya adalah MEAN
- pada crosstab, fungsi aggregate DEFAULT nya adalah COUNT

In [89]:
pd.crosstab(df['category'], columns='count')

col_0                 count
category                   
Fabric Care           36000
Rice                  12000
Sugar/Flavored Syrup  24000

In [91]:
pd.pivot_table(data=df, index='category')
# secara otomatis akan mengeluarkan SELURUH KOLOM NUMERIK dan dihitung MEAN nya

Total     discount  quantity  receipts_item_id  \
category                                                                      
Fabric Care           24057.452666  1316.550667  1.379444      2.459785e+07   
Rice                  90366.554917   835.305750  1.332917      2.457950e+07   
Sugar/Flavored Syrup  21329.772002   164.106542  1.712958      2.458355e+07   

                        unit_price     year  
category                                     
Fabric Care           17893.793214  2017.75  
Rice                  70013.146313  2017.75  
Sugar/Flavored Syrup  12645.066024  2017.75

In [92]:
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  \
receipt_id                                                                      
9622257     supermarket    128000.0         0         1  July  2018    Sunday   
9446359      minimarket    102750.0         0         1  July  2018    Sunday   
9470290     supermarket     64000.0         0         3  July  2018    Sunday   
9643416      minimarket     65000.0         0         1  July  2018   Tuesday   
9692093     supermarket    124500.0         0         1  July  2018  Thursday   

           quarter     Total          custom  
receipt_id                                    
9622257     2018Q3  128000.0  July - 21 : 21  
9446359     2018Q3  102750.0  July - 16 : 16  
9470290     2018Q3  192000.0  July - 12 : 12  
9643416     2018Q3   65000.0  July - 08 : 08  
9692093     2018Q3  124500.0  July - 11 : 11

In [93]:
def discount(x):
    return 0.15 * x

In [94]:
df['discount'] = df['unit_price'].apply(discount)
df.head()

receipts_item_id       purchase_time category sub_category  \
receipt_id                                                               
9622257             32369294 2018-07-22 21:19:00     Rice         Rice   
9446359             31885876 2018-07-15 16:17:00     Rice         Rice   
9470290             31930241 2018-07-15 12:12:00     Rice         Rice   
9643416             32418582 2018-07-24 08:27:00     Rice         Rice   
9692093             32561236 2018-07-26 11:28:00     Rice         Rice   

                 format  unit_price  discount  quantity month  year       day  \
receipt_id                                                                      
9622257     supermarket    128000.0   19200.0         1  July  2018    Sunday   
9446359      minimarket    102750.0   15412.5         1  July  2018    Sunday   
9470290     supermarket     64000.0    9600.0         3  July  2018    Sunday   
9643416      minimarket     65000.0    9750.0         1  July  2018   Tuesday   
9692093     supermarket    124500.0   18675.0         1  July  2018  Thursday   

           quarter     Total          custom  
receipt_id                                    
9622257     2018Q3  128000.0  July - 21 : 21  
9446359     2018Q3  102750.0  July - 16 : 16  
9470290     2018Q3  192000.0  July - 12 : 12  
9643416     2018Q3   65000.0  July - 08 : 08  
9692093     2018Q3  124500.0  July - 11 : 11