In [1]:
import numpy as np
import pandas as pd

## Numpy adalah array dan bersifat elementwise -> operasi dilakukan ke setiap elemen dari arry

In [2]:
list_sample = [1, 2, 3, 4, 5]
array_sample = np.array([1, 2, 3, 4, 5])

print(f"list -> {2 * list_sample}")
print(f"array -> {2 * array_sample}")

list -> [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
array -> [ 2  4  6  8 10]


## Range dari numpy dapat menggunakan step bernilai float


In [3]:
np.arange(5, 50, 2.5)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. ,
       32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5])

In [4]:
range(5, 50, 2.5)

TypeError: 'float' object cannot be interpreted as an integer

## np.linspace

In [ ]:
np.linspace(1, 10, 4)

## Array Multi Dimensi --> Matrix

In [5]:
# List
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
aNum = np.array(a)
aNum

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

aNum = np.array(a)
bNum = np.array(b)

In [11]:
aNum, bNum

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [12]:
a[4]

5

In [2]:
df = pd.read_csv('data/Sales.csv')
df.head()

Country Region Sales Person    Date of Purchase     Total  Quantity
0   India   East         John    3/1/2013 0:00:00  26000000       567
1   China  North         Bill  12/29/2016 0:00:00    100000      3000
2      UK   East       Thomas   1/13/2014 0:00:00    120000       345
3   Nepal   East         John    4/2/2010 0:00:00    200000      1000
4  Africa   East         Bill  10/16/2015 0:00:00    220000       123

In [3]:
df.describe()

Total     Quantity
count  2.000000e+01    20.000000
mean   1.489000e+06  1479.300000
std    5.769521e+06  2279.447258
min    1.000000e+05   123.000000
25%    1.500000e+05   345.000000
50%    2.200000e+05   946.000000
75%    2.450000e+05  1000.000000
max    2.600000e+07  7890.000000

In [5]:
df.describe().T

count       mean           std       min       25%       50%  \
Total      20.0  1489000.0  5.769521e+06  100000.0  150000.0  220000.0   
Quantity   20.0     1479.3  2.279447e+03     123.0     345.0     946.0   

               75%         max  
Total     245000.0  26000000.0  
Quantity    1000.0      7890.0

In [9]:
df.describe(include='O')

Country Region Sales Person  Date of Purchase
count       20     20           20                20
unique      11      3            3                20
top      Nepal   East         John  7/7/2014 0:00:00
freq         4      9            7                 1